// <auto-generated />
using Mall.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mall.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211105024029_DatabaseCreation")]
    partial class DatabaseCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mall.Models.EntityModels.PmsProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("描述");

                    b.Property<string>("Icon")
                        .HasColumnType("varchar(255)")
                        .HasComment("图标");

                    b.Property<string>("Keywords")
                        .HasColumnType("varchar(255)")
                        .HasComment("关键字");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasComment("分类级别： 0->1级；1->2级");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(64)")
                        .HasComment("名称");

                    b.Property<int>("NavStatus")
                        .HasColumnType("int")
                        .HasComment("是否显示在导航栏：0->不显示；1->显示");

                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasComment("上级分类的编号：0 表示一级分类");

                    b.Property<int>("ProductCount")
                        .HasColumnType("int")
                        .HasComment("商品数量");

                    b.Property<string>("ProductUnit")
                        .HasColumnType("varchar(64)")
                        .HasComment("商品单位");

                    b.Property<int>("ShowStatus")
                        .HasColumnType("int")
                        .HasComment("显示状态：0->不显示；1->显示");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasComment("排序");

                    b.HasKey("Id");

                    b.ToTable("PmsProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
